name: chainlink-testing-framework-test-runner
description: Common runner for chainlink-testing-framework based tests
inputs:
  artifacts_location:
    required: false
    description: Location of where error logs are written
    default: ./tests/e2e/logs
  test_command_to_run:
    required: true
    description: The command to run the tests
  test_download_vendor_packages_command:
    required: false
    description: The command to download the go modules
    default: make download
  test_download_ginkgo_command:
    required: false
    description: The command to download Ginkgo
    default: make install
  cl_repo:
    required: false
    description: The Chainlink ecr repository to use
    default: public.ecr.aws/z0b1w9r9/chainlink
  cl_image_tag:
    required: false
    description: The chainlink image to use
    default: develop
  build_gauntlet_command:
    required: false
    description: How to build gauntlet if necessary
    default: 'false'
  download_contract_artifacts_path:
    required: false
    description: Path where the contract artifacts need to be placed
    default: 'none'
  publish_report_paths:
    required: false
    description: The path of the output report
    default: "./tests-smoke-report.xml"
  publish_check_name:
    required: false
    description: The check name for publishing the reports
    default: Smoke Test Results
  token:
    required: false
    description: The GITHUB_TOKEN for the workflow
    default: ${{ github.token }}
  QA_AWS_REGION:
    required: true
    description: The AWS region to use
  QA_AWS_ROLE_TO_ASSUME:
    required: true
    description: The AWS role to assume
  QA_KUBECONFIG:
    required: true
    description: The kubernetes configuration to use
  CGO_ENABLED:
    required: false
    description: Whether to have cgo enabled
    default: "0"


runs:
  using: composite
  steps:
    - uses: smartcontractkit/tool-versions-to-env-action@v1.0.7
      id: tool-versions
    - name: Setup go ${{ steps.tool-versions.outputs.golang_version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.tool-versions.outputs.golang_version }}
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.QA_AWS_REGION }}
        role-to-assume: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.QA_KUBECONFIG }}
    - name: Tool Versions
      shell: bash
      run: |
        aws --version
        aws sts get-caller-identity
        kubectl version --short
    - name: Cache Vendor Packages
      uses: actions/cache@v3
      id: cache-packages
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Download Go Vendor Packages
      if: steps.cache-packages.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.test_download_vendor_packages_command }}
    - name: Install Ginkgo CLI
      if: steps.cache-packages.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.test_download_ginkgo_command }}
    - name: Download Artifacts
      if: inputs.download_contract_artifacts_path != 'none'
      uses: actions/download-artifact@v3
      with:
        name: artifacts
        path: ${{ inputs.download_contract_artifacts_path }}
    - name: Generate gauntlet executable
      if: inputs.build_gauntlet_command != 'false'
      shell: bash
      run: ${{ inputs.build_gauntlet_command }}
    - uses: azure/setup-helm@v3
      with:
        version: 'v3.9.0'
      id: install
    - name: Add QA charts repo
      shell: bash
      run: helm repo add chainlink-qa https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/
    - name: Run Tests
      shell: bash
      env:
        CHAINLINK_IMAGE: ${{ inputs.cl_repo }}
        CHAINLINK_VERSION: ${{ inputs.cl_image_tag }}
        CGO_ENABLED: ${{ inputs.CGO_ENABLED }}
      run: |
        PATH=$PATH:$(go env GOPATH)/bin
        export PATH
        ${{ inputs.test_command_to_run }}
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: ${{ inputs.publish_report_paths }}
        github_token: ${{ inputs.token }}
        check_name: ${{ inputs.publish_check_name }}
        comment_mode: create new
    - name: Publish Artifacts
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-logs
        path: ${{ inputs.artifacts_location }}
