name: go-mod-tidy
description: Common go mod tidy check, requires go to already be setup and any caching to already have been done
inputs:
  go_mod_path:
    required: false
    description: The go.mod file path
    default: "go.mod"

runs:
  using: composite
  steps:
    - name: Tidy and check files
      shell: bash
      run: |
        # find test go root by using the go_mod_path and change to that directory
        TEST_LIB_PATH="${{ inputs.go_mod_path }}"
        if [ "${#TEST_LIB_PATH}" -gt "6" ]; then
            TEST_LIB_PATH=${TEST_LIB_PATH%go.mod}
            cd "${TEST_LIB_PATH}"
        fi
        go mod tidy
        git diff --stat --exit-code

