name: chainlink-testing-framework-cleanup
description: Common runner for cleaning up a namespace
inputs:
  triggered_by:
    required: true
    description: The triggered-by label for the k8s namespace
    default: ci

runs:
  using: composite
  steps:
    - name: cleanup k8s cluster namespaces
      shell: bash
      run: |
        echo "looking for namespaces"
        ITEMS=$(kubectl get ns -l=triggered-by=${{ inputs.triggered_by }}-${{ github.event.pull_request.number || github.run_id }} -o jsonpath='{.items}')
        COUNT=$(echo "${ITEMS}" | jq '. | length')
        echo "found ${COUNT} namespaces to cleanup"
        for ((i=0;i<${COUNT};i++)); do
          name=$(echo "${ITEMS}" | jq -r ".[${i}].metadata.name")
          echo "deleting namespace: ${name}"
          kubectl delete ns "${name}" || echo "namespace no longer exists"
        done
        echo "completed cleanup"
