name: Build Docker Image and push to ECR
description: Common docker image builder for building chainlink docker images
inputs:
  context:
    required: false
    default: "."
    description: The context of the docker build
  tags:
    required: true
    description: The full docker tag list to use for the push to ecr, new line separated
  file:
    required: true
    description: The path to the dockerfile to build
  build-args:
    required: false
    description: Comma separated build-args for the docker build to pass through, example KEY1=VAL1,KEY2=VAL2,...
  push:
    required: true
    default: "true"
    description: Whether we should push the image or not
  AWS_REGION:
    required: true
    description: The AWS region to use
  AWS_ROLE_TO_ASSUME:
    required: true
    description: The AWS role to assume

runs:
  using: composite
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@010d0da01d0b5a38af31e9c3470dbfdabdecca3a # v4.0.1
      with:
        aws-region: ${{ inputs.AWS_REGION }}
        role-to-assume: ${{ inputs.AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
        mask-aws-account-id: true
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1
      with:
        mask-password: "true"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
    - name: Build and Push
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
      id: build-image
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        build-args: ${{ inputs.build-args }}
        tags: ${{ inputs.tags }}
        push: ${{ inputs.push }}
