name: setup-run-tests-environment
description: Common test env setup
inputs:
  test_download_vendor_packages_command:
    required: false
    description: The command to download the go modules
    default: make download
  go_mod_path:
    required: false
    description: The go.mod file path
    default: "go.mod"
  aws_registries:
    required: false
    description: AWS registries to log into for the test if needed
  QA_AWS_REGION:
    required: true
    description: The AWS region to use
  QA_AWS_ROLE_TO_ASSUME:
    required: true
    description: The AWS role to assume
  QA_KUBECONFIG:
    required: true
    description: The kubernetes configuration to use

runs:
  using: composite
  steps:
    # Go setup and caching
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version-file: ${{ inputs.go_mod_path }}
        check-latest: true
    - name: Cache Vendor Packages
      uses: actions/cache@v3
      id: cache-packages
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
          ~/go/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Tidy and check files
      shell: bash
      run: |
        # find test go root by using the go_mod_path and change to that directory
        TEST_LIB_PATH="${{ inputs.go_mod_path }}"
        if [ "${#TEST_LIB_PATH}" -gt "6" ]; then
            TEST_LIB_PATH=${TEST_LIB_PATH%go.mod}
            cd "${TEST_LIB_PATH}"
        fi
        go mod tidy
        git diff --stat --exit-code
    - name: Download Go Vendor Packages
      if: steps.cache-packages.outputs.cache-hit != 'true'
      shell: bash
      run: ${{ inputs.test_download_vendor_packages_command }}

    # Setup AWS cred and K8s context
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@e1e17a757e536f70e52b5a12b2e8d1d1c60e04ef # 2.0.0
      with:
        aws-region: ${{ inputs.QA_AWS_REGION }}
        role-to-assume: ${{ inputs.QA_AWS_ROLE_TO_ASSUME }}
        role-duration-seconds: 3600
    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ inputs.QA_KUBECONFIG }}

    # Login to AWS ECR registries if needed
    - name: Login to Amazon ECR
      if: ${{ inputs.aws_registries }}
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@2f9f10ea3fa2eed41ac443fee8bfbd059af2d0a4 # v1.6.0
      with:
        registries: ${{ inputs.aws_registries }}
      env:
        AWS_REGION: ${{ inputs.QA_AWS_REGION }}

    # Helm Setup
    - uses: smartcontractkit/tool-versions-to-env-action@v1.0.8
      id: tool-versions
    - uses: azure/setup-helm@v3
      with:
        version: v${{ steps.tool-versions.outputs.helm_version }}
    - name: Add required helm charts including chainlink-qa
      shell: bash
      run: |
        helm repo add bitnami https://charts.bitnami.com/bitnami
        helm repo add chainlink-qa https://raw.githubusercontent.com/smartcontractkit/qa-charts/gh-pages/

    # Display tool versions
    - name: Tool Versions
      shell: bash
      run: |
        go version
        aws --version
        kubectl version
        helm version
        helm repo list
