name: Cleanup Cancel Test
on:
  pull_request:
jobs:
  can_cancel_cleanup:
    name: Can Cleanup and Cancel Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: old should not download
        run: |
          CHECK=$(which cat || true)
          echo "check = '${CHECK}'"
          if [[ -z "${CHECK}" ]]; then
            echo "should download"
          fi
      - name: new should not download
        run: |
          CHECK=$(which cat || echo "not found")
          echo "check = '${CHECK}'"
          if [[ "${CHECK}" == *"not found" ]]; then
            echo "should download"
          fi
      - name: old should download
        run: |
          CHECK=$(which catadfadsf || true)
          echo "check = '${CHECK}'"
          if [[ -z "${CHECK}" ]]; then
            echo "should download"
          fi
      - name: new should download
        run: |
          CHECK=$(which catadfadsf || echo "not found")
          echo "check = '${CHECK}'"
          if [[ "${CHECK}" == *"not found" ]]; then
            echo "should download"
          fi
