name: 'semver-compare-build-ci'
on:
  pull_request:
    paths:
      - '.github/workflows/semver-compare-ci.yaml'
      - 'semver-compare/**'
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - '.github/workflows/semver-compare-ci.yaml'
      - 'semver-compare/**'

defaults:
  run:
    shell: bash
    working-directory: ./semver-compare

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - run: npm ci
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - uses: ./semver-compare/
        with:
          version1: 2.0.0
          operator: gt
          version2: 1.0.0
