name: 'semver-compare-build-ci'
on:
  pull_request:
    paths:
      - '.github/workflows/semver-compare-ci.yaml'
      - 'semver-compare/**'
  push:
    branches:
      - main
      - 'release/*'
    paths:
      - '.github/workflows/semver-compare-ci.yaml'
      - 'semver-compare/**'

defaults:
  run:
    shell: bash
    working-directory: ./semver-compare

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - run: npm ci
      - run: npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - uses: ./semver-compare/
        with:
          version1: 2.0.0
          operator: gt
          version2: 1.0.0
